In [1]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../Milestone 1 - Data_Collection_&_Preparation/encoded.csv')

In [3]:
x = data.drop('Stages',axis=1)
y = data['Stages']
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [4]:
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = {}

In [5]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
print("Logistic Regression:")
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
accuracy['Logistic Regression'] = accuracy_score(y_test,y_pred)

Logistic Regression:
Accuracy: 0.9518518518518518
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00       113
           2       1.00      0.85      0.92        85
           3       0.79      1.00      0.88        49

    accuracy                           0.95       270
   macro avg       0.95      0.96      0.95       270
weighted avg       0.96      0.95      0.95       270

Confusion Matrix:
 [[ 23   0   0   0]
 [  0 113   0   0]
 [  0   0  72  13]
 [  0   0   0  49]]


In [6]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)
print("Decision Tree:")
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
accuracy['Decision Tree'] = accuracy_score(y_test,y_pred)

Decision Tree:
Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00       113
           2       1.00      1.00      1.00        85
           3       1.00      1.00      1.00        49

    accuracy                           1.00       270
   macro avg       1.00      1.00      1.00       270
weighted avg       1.00      1.00      1.00       270

Confusion Matrix:
 [[ 23   0   0   0]
 [  0 113   0   0]
 [  0   0  85   0]
 [  0   0   0  49]]


In [7]:
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
print("Random Forest:")
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
accuracy['Random Forest'] = accuracy_score(y_test,y_pred)

Random Forest:
Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00       113
           2       1.00      1.00      1.00        85
           3       1.00      1.00      1.00        49

    accuracy                           1.00       270
   macro avg       1.00      1.00      1.00       270
weighted avg       1.00      1.00      1.00       270

Confusion Matrix:
 [[ 23   0   0   0]
 [  0 113   0   0]
 [  0   0  85   0]
 [  0   0   0  49]]


In [8]:
svm = SVC()
svm.fit(X_train,y_train)
y_pred = svm.predict(X_test)
print("Logistic Regression:")
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
accuracy['SVM'] = accuracy_score(y_test,y_pred)

Logistic Regression:
Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00       113
           2       1.00      1.00      1.00        85
           3       1.00      1.00      1.00        49

    accuracy                           1.00       270
   macro avg       1.00      1.00      1.00       270
weighted avg       1.00      1.00      1.00       270

Confusion Matrix:
 [[ 23   0   0   0]
 [  0 113   0   0]
 [  0   0  85   0]
 [  0   0   0  49]]


In [9]:
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
print("KNN:")
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
accuracy['KNN'] = accuracy_score(y_test,y_pred)

KNN:
Accuracy: 0.9814814814814815
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.78      0.88        23
           1       0.96      1.00      0.98       113
           2       1.00      1.00      1.00        85
           3       1.00      1.00      1.00        49

    accuracy                           0.98       270
   macro avg       0.99      0.95      0.96       270
weighted avg       0.98      0.98      0.98       270

Confusion Matrix:
 [[ 18   5   0   0]
 [  0 113   0   0]
 [  0   0  85   0]
 [  0   0   0  49]]


In [10]:
rc = RidgeClassifier()
rc.fit(X_train,y_train)
y_pred = rc.predict(X_test)
print("Ridge Classifier:")
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
accuracy['Ridge Classifier'] = accuracy_score(y_test,y_pred)

Ridge Classifier:
Accuracy: 0.9
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.57      0.72        23
           1       0.92      1.00      0.96       113
           2       0.93      0.87      0.90        85
           3       0.80      0.88      0.83        49

    accuracy                           0.90       270
   macro avg       0.91      0.83      0.85       270
weighted avg       0.91      0.90      0.90       270

Confusion Matrix:
 [[ 13  10   0   0]
 [  0 113   0   0]
 [  0   0  74  11]
 [  0   0   6  43]]


In [11]:
nb = GaussianNB()
nb.fit(X_train,y_train)
y_pred = nb.predict(X_test)
print("Naive Bayes:")
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
accuracy['Naive Bayes'] = accuracy_score(y_test,y_pred)

Naive Bayes:
Accuracy: 0.8444444444444444
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00       113
           2       1.00      0.51      0.67        85
           3       0.54      1.00      0.70        49

    accuracy                           0.84       270
   macro avg       0.88      0.88      0.84       270
weighted avg       0.92      0.84      0.84       270

Confusion Matrix:
 [[ 23   0   0   0]
 [  0 113   0   0]
 [  0   0  43  42]
 [  0   0   0  49]]
